# -*- encoding: utf-8 -*-

=begin
#DevCycle Bucketing API

#Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "devcycle-server-sdk/version"

Gem::Specification.new do |s|
  s.name        = "devcycle-server-sdk"
  s.version     = DevCycle::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DevCycleHQ"]
  s.email       = ["support@devcycle.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "DevCycle Bucketing API Ruby Gem"
  s.description = "Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end

curl -u DevCycle https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials
