=begin
#DevCycle Bucketing API

#Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DevCycle::InlineResponse201
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DevCycle::InlineResponse201 do
  let(:instance) { DevCycle::InlineResponse201.new }

  describe 'test an instance of InlineResponse201' do
    it 'should create an instance of InlineResponse201' do
      expect(instance).to be_instance_of(DevCycle::InlineResponse201)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
