# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module DevCycle::Configuration::Rails; end
module LocalBucketing::Wasmtime::Engine; end
module LocalBucketing::Wasmtime::Linker; end
module LocalBucketing::Wasmtime::Module; end
module LocalBucketing::Wasmtime::Store; end
module LocalBucketing::Wasmtime::WasiCtxBuilder; end
