# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variableForUser.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("variableForUser.proto", :syntax => :proto3) do
    add_message "proto.NullableString" do
      optional :value, :string, 1
      optional :isNull, :bool, 2
    end
    add_message "proto.NullableDouble" do
      optional :value, :double, 1
      optional :isNull, :bool, 2
      optional :dummy, :string, 3
    end
    add_message "proto.CustomDataValue" do
      optional :type, :enum, 1, "proto.CustomDataType"
      optional :boolValue, :bool, 2
      optional :doubleValue, :double, 3
      optional :stringValue, :string, 4
    end
    add_message "proto.NullableCustomData" do
      map :value, :string, :message, 1, "proto.CustomDataValue"
      optional :isNull, :bool, 2
    end
    add_message "proto.VariableForUserParams_PB" do
      optional :sdkKey, :string, 1
      optional :variableKey, :string, 2
      optional :variableType, :enum, 3, "proto.VariableType_PB"
      optional :user, :message, 4, "proto.DVCUser_PB"
      optional :shouldTrackEvent, :bool, 5
    end
    add_message "proto.DVCUser_PB" do
      optional :user_id, :string, 1
      optional :email, :message, 2, "proto.NullableString"
      optional :name, :message, 3, "proto.NullableString"
      optional :language, :message, 4, "proto.NullableString"
      optional :country, :message, 5, "proto.NullableString"
      optional :appBuild, :message, 6, "proto.NullableDouble"
      optional :appVersion, :message, 7, "proto.NullableString"
      optional :deviceModel, :message, 8, "proto.NullableString"
      optional :customData, :message, 9, "proto.NullableCustomData"
      optional :privateCustomData, :message, 10, "proto.NullableCustomData"
    end
    add_message "proto.SDKVariable_PB" do
      optional :_id, :string, 1
      optional :type, :enum, 2, "proto.VariableType_PB"
      optional :key, :string, 3
      optional :boolValue, :bool, 4
      optional :doubleValue, :double, 5
      optional :stringValue, :string, 6
      optional :evalReason, :message, 7, "proto.NullableString"
    end
    add_enum "proto.VariableType_PB" do
      value :Boolean, 0
      value :Number, 1
      value :String, 2
      value :JSON, 3
    end
    add_enum "proto.CustomDataType" do
      value :Bool, 0
      value :Num, 1
      value :Str, 2
      value :Null, 3
    end
  end
end

module Proto
  NullableString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NullableString").msgclass
  NullableDouble = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NullableDouble").msgclass
  CustomDataValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CustomDataValue").msgclass
  NullableCustomData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NullableCustomData").msgclass
  VariableForUserParams_PB = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.VariableForUserParams_PB").msgclass
  DVCUser_PB = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DVCUser_PB").msgclass
  SDKVariable_PB = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SDKVariable_PB").msgclass
  VariableType_PB = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.VariableType_PB").enummodule
  CustomDataType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CustomDataType").enummodule
end
