name: Run Test Harness

on:
  pull_request:
    branches: [ main ]

jobs:
  harness-tests:
    name: Harness Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST_IP: '172.17.0.1'
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          repository: DevCycleHQ/test-harness
          token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Write variables to .env file
        run: |
          if [ ! -f ".env" ]
          then 
           echo "SDK_GITHUB_SHA='${{ github.event.inputs.sha }}'" >> ".env"
           echo "SDKS_TO_TEST='${{ github.event.inputs.sdk }}'" >> ".env"
          fi
      - name: Install Dependencies
        run: yarn install
      - name: Run All Tests
        run: yarn test:ci