name: Run Test Harness

on:
  pull_request:
    branches: [main]

jobs:
  harness-tests:
    name: Harness Tests
    runs-on:
      labels: ubuntu-latest-4-core
    steps:
      - uses: DevCycleHQ/test-harness@main
        with:
          sdks-to-test: ruby
          sdk-github-sha: ${{github.event.pull_request.head.sha}}
          sdk-capabilities: '{ "Ruby": ["clientCustomData", "v2Config", "variableFeatureId", "allVariables", "allFeatures", "evalReason", "cloudEvalReason", "eventsEvalReason"]}'
