name: Run Test Harness

on:
  pull_request:
    branches: [ main ]

jobs:
  harness-tests:
    name: Harness Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DevCycleHQ/test-harness@caa0ba85e9a2e09d67dd0cfa2b67fe750b5b1c99
        with:
          sdk: nodejs
          sdk-github-sha: ${GITHUB_SHA}
          github-token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
